global using MediatR;
global using System.Linq;
global using System.Threading.Tasks;
global using RideAdministration.Domain.SeedWork;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Storage;
global using System;
global using System.Threading;
global using System.Data;